version: "3.8"

services:
  phase-ten:
    build:
      context: .
      dockerfile: Dockerfile
    image: phase-ten:v2.2
    container_name: phase-ten
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
