version: "3.8"

services:
  tenstages:
    build:
      context: .
      dockerfile: Dockerfile
    image: tenstages:v6.1
    container_name: tenstages
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
      - PORT=6969
